version: '3.8'

services:
  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: superset_app
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=supersecretkey
      - SUPERSET_DATABASE_URI=postgresql+psycopg2://superset:Sup3rs3t@10.5.0.124:5432/superset
    volumes:
      - superset_home:/app/superset_home

volumes:
  superset_home:
