version: '3.8'

services:
  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: superset_app
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=supersecretkey
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - superset_db

  superset_db:
    image: postgres:15
    container_name: superset_db
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - superset_db:/var/lib/postgresql/data

volumes:
  superset_db:
  superset_home:
